### ISSUE TITLE
Small Sugbu Easter Egg/Setup Bug

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#11]
As what I'm assuming is a holdover from vanilla, Sugbu (i.e. the Phillipines) starts the game with trinket healthcare. 

In terms of flavor for them, maybe add an extra bonus cash+research+tech if they manage to reclaim their cores from Tungning and/or Scandinavia?

**Comment by TheDeNuke** [comment]
Huh. Its not actually a holdover. This was manually entered by someone.

WAD. I guess?
