### ISSUE TITLE
Unintended (?) Patriot Defection

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#12]
I just had all of Egypt south of Bani Suwayf defect from the Ottomans and flip to Circassia, due to I assume the Mamaluk pops revolting. While this is hilarious and awesome (and not something I've noticed happening frequently), I figured it's notable enough to warrant a "WAD" confirmation or naw.

**Comment by TheDeNuke** [comment]
RebelTypes.txt

Always the bane of my existance.

**Comment by TheDeNuke** [comment]
I'll just WAD it because I can't find a reason why this would happen. It just seems to be a unintended result of patriot rebels.
