### ISSUE TITLE
Bug: French cores on Algeria

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#19]
I've noticed a couple times that should France form, it will often get a smattering of cores on Aragonese Algeria. Is this WAD or a holdover from a vanilla HPM port?

**Comment by TheDeNuke** [comment]
@tbg2021 

As I've said on many issues previously this seems to be yet another example of exceptionally strange happenings. However, as I've also said in the past I need to know WHEN these events are happening since there practically is nothing in the documents about FRA cores on North Africa.

**Comment by TheDeNuke** [comment]
WHICH French Formation was it.

That's the real question that I've been trying to ask. There is the PRV Decision and the Total Revolution.

**Comment by tbg2021** [comment]
IIRC, it happened after England had successfully broke away for some time,
and then Ireland also left due to normal rebels. I believe that they got
the cores in Algeria after taking whatever decision also gives France cores
on Occitania, but I don't have any saves around the time I noticed it to
double check.
