### ISSUE TITLE
Bug: Scottish Petition + Puppet England

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#20]
A puppeted England will still get the alliance with Scotland (as well as weight the entire chain towards independence, I believe) and go to war with Scandinavia, despite still being a satellite.

**Comment by TheDeNuke** [comment]
Interesting.

I'll just put a exception on the scripting that it can't trigger the independence event for ENL if its a puppet.

**Comment by TheDeNuke** [comment]
Resolved
