### ISSUE TITLE
Bug: Only way to get iron artillery factory is via civilizing reform

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#22]
There's no invention to unlock them, or some other of the factories for the various good types. Dunno if it's intended to have removed them or intended to have them in. Semi-related, Spices seems to be in a permanent oversupply, maybe increase demand or reduce their prevalence?

**Comment by TheDeNuke** [comment]
@tbg2021 
Added iron artillery factory to the correct invention.

Spices are a economic balance issue so I'm going to need the exact percentages regarding the overproduction.

Tell me the exact other missing factories/goods factories.

**Comment by tbg2021** [comment]
As far as I can tell, all the mid-late game substitution factories from (iirc) PDM are unactivated. While not an exhaustive list, this includes things noted in the machine parts "possible demand" list such as Advanced Luxury Clothes, advanced luxury furniture, advanced machine parts,iron machine parts, late small arms factory, small arms factory, and perhaps a couple other I'm missing. The lack of these may contribute to late game low demand for iron and derivative supply chain goods. 

Also, I meant under demanded rather than oversupplied in regards to spices. Pulling from a static point, the econ analyzer has the spices in one save at 101.29% overproduction % (100% being a perfect supply/demand match), which AFAIK is somewhat misleading as production follows demand often in this game (afaik). This is notable because in most other versions of v2 I've played, spices usually hover around 16 pounds and are an almost no brainer select for the "colonial plantations crop choice" event, wheras in this version I never pick them. While that's good balancing on the rest of the items, I'd suggest increasing demand of them on the lower and middle classes, which ramps up as the game goes on. Compare spices to coffee in this version, which I've never seen supply even come close to the total demand. I'm guessing that there's a factor off in the spice demand, as (from the same save) soldiers demand a total of .08 spices daily but 12.74 coffee daily, from a total pop of 2.26m soldiers. Labourers demand 559.12 coffee daily while only wanting 5.31 per day of spices. I believe this ends up causing a widespread amount of underemployement in spice RGOs, especially  in uncivs that start with large spice supplies that would otherwise give them a small early game buffer of cash flow.

**Comment by tbg2021** [comment]
Also Steel machine parts factory & steel artillery factory

**Comment by TheDeNuke** [comment]
I think it will be easier for me just to lower the spices RGO output by at least 50 percent and seeing what that does. I'm not a fan of tweaking the pop demand to say the least due to how quickly doing so can go completely out of control.

I'll work on adding the Steel Machine Parts Factory and Steel Artillery Factory to the mix.

**Comment by TheDeNuke** [comment]
I activated the advanced machine parts factory in the 1920 bracket and the steel machine parts factory in the 1850 bracket.

I'll work on the other advanced factories as I go along.

**Comment by TheDeNuke** [comment]
@tbg2021 

Turns out that DBZ deactivates these factories. They are present in PDM but not in DBZ.

So, I guess I'll be deliberately reverting the changes because reactivating these factories could fuck with the economic balance too much. Mostly in the fact that the player is only likely to build these factories.

**Comment by TheDeNuke** [comment]
Expect for the Iron and Steel Artillery Factory. Of course.

**Comment by TheDeNuke** [comment]
I'll close this for now. If you have any issues regarding the value of the spices then feel free to post another issue. I've halved the spice production for now.

**Comment by tbg2021** [comment]
Spice works well now. Adding to the requested list, Rubber Boots is another non-enabled factory
