### ISSUE TITLE
Bug: Republics vs Bohemia in the Second German Revolution

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#24]
Should the Danubians get inspired to revolt due to a fairly successful DUA explosion + NET rebellion (I love the chaos of this, btw), they seem to get stuck in a standoff where the former DUA republics and NET are collectively much stronger than Bohemia, but are unable to reach it and actually help out the Danubians because they're both landlocked. Maybe some sort of negotiated settlement event could be added in this rare case?

**Comment by tbg2021** [comment]
Alternatively, in the rare but not unheard of case should this initial scenario occur (the rhineland then has a successful republican revolt due to Burgundy just having lost its north and been trampled in a hellwar between everyone that the Rhineland sat out), the Rhineish could champion the cause of the Danubians and either reform or (have the option to) join the war on the side of the Danubian coalliton.

**Comment by TheDeNuke** [comment]
How many layers of rare are we on at this point?

I don't actually think that SGF is meant to survive in the far majority of scenarios unless ITA is directly supporting them, but I'll setup the NGF revolt to trigger if the total revolution scenario occurs which should allow the survival of SGF if Bohemia is distracted.

Also, I refuse to give RHI more content on the basis that you are talking about a level of rare that's basically on the same scale as the Revolt of the Dukes winning and utterly destroying BRG.

**Comment by TheDeNuke** [comment]
I set the NGF revolt to autotrigger if SCA does not own the North and the Total Revolution is happening.

**Comment by TheDeNuke** [comment]
Along with BRG being rigged to not join in the SGF war if the Total Revolution is happening. That might be enough to break BOH. Hopefully.
