### ISSUE TITLE
Enhancement: Lanfang Republic National Value from Order to Liberty

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#25]
Seems more appropriate to their status as republic and OTL timeline, but I'll admit I'm not familiar with their existing (?) lore in ttl

**Comment by TheDeNuke** [comment]
This is not the OTL Lanfang and is basically nothing to do with freedom and liberty. Its effectively a Chinese colony without a King and has very un-democratic reforms at the start.

This is WAD
