### ISSUE TITLE
Enhancement: Give Joseon Shogunate in the Japan event tree time to muster

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#29]
As is they form and immediately DoW, which makes Japan win 100% of the time without much effort. Which is a shame, because the other path sounds interesting.

**Comment by tbg2021** [comment]
Oh, and resources, if they don't already get one of those "you are a new rebellion, here's your warchest and 10 prestige"

**Comment by TheDeNuke** [comment]
I'll war-chest them.

Do you know I literally gave them a single other state in Japan originally and they always won? Its so strange how balance can just flip like that so easily.

**Comment by TheDeNuke** [comment]
I gave them a month and a Warchest. 

That's as far as I'll go. Hopefully it enables the TKG AI to not completely screw up.
