### ISSUE TITLE
Early Game Persian Prestige

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#3]
I believe there's a shifted decimal place somewhere in the various early game Persian civil war events, as I've seen both AFG and QAJ with prestige in the 10000s in the 1840-1850s as a result.

**Comment by TheDeNuke** [comment]
Yikes.

That seems more like a missing event flag.

**Comment by TheDeNuke** [comment]
Yeah. It was a decision without a flag lock.

Resolved.
