### ISSUE TITLE
Bug: Decision "Unify with Navarra" has broken OR condition

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#30]

**Comment by TheDeNuke** [comment]
I had to rework that whole thing so it worked with the other two potential tags, and then bug check it several times.

Turns out I clearly did not bug check it enough.

**Comment by TheDeNuke** [comment]
Strange. That decisions seems normal and has no issue. Nor is Validator coming up with any issues regarding that decision.

**Comment by TheDeNuke** [comment]
I removed the "exists = NAV" in the allow since its redundant due to the potential also having "exists = NAV". 

Generally it may seem broken but there might also be the factor that if it does not exist and you don't directly own the capital of NAV. The decision will not appear.

**Comment by TheDeNuke** [comment]
@tbg2021 

It... should... work now. Just create another issue if for some reason its still broken.

**Comment by tbg2021** [comment]
Nah, it was that in my case as Spain I had just accepted the Catalans and
annexed the Basque country as well with my cores already existing, but the
decision still available. What the decision in its previous buggy state had
let me do in effect was release Navarra as a buffer satellite so the DUA
wouldn't immediately curbstomp me, then reincorporate later with no real
penalty.
