### ISSUE TITLE
Enhancement: Flag to Auto-deny all the excavation requests

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#32]
Sometimes I just wanna hoard all the pyramid knowledge to myself, ya know?

**Comment by TheDeNuke** [comment]
You mean so that a player can lock all the events/decisions by virtue of pressing a "fuck you and your excavations" event option.

I can do that.

**Comment by TheDeNuke** [comment]
Done.

Just remember if you fall under the sphere of a GP then they can force it.
