### ISSUE TITLE
Suggestion: Give AI Zhourao Australia

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#6]
IMO, adding a clause that allows for the AI to take the various "claim the continent decisions" if a certain amount of time has past (1870? 1880?). As is it's free real estate for the player, as the AI has a crapshoot chance of ever getting around to grabbing the right series of techs and infrastructure investments, and the other colonial powers wont touch it because of the cores. There's a similar but less pronounced issue in the heart of africa as well.

**Comment by TheDeNuke** [comment]
I'm not stopping you from taking parts of Zhourao.

The HOI4 mod has the European colonial powers actually colonizing the western part of Zhourao, so I guess it makes sense if the player is smart enough to beat Zhourao in taking the west.

Consider this as a WAD. At most I might consider allowing the AI colonial powers to take chunks of the land themselves under specific circumstances.
