### ISSUE TITLE
Core Assimilation

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#8]
The event where you can remove others cores is busted, in that regardless of the citizenship type of the ruling party it'll always self-terminate a couple months after one attempts to start assimilating.

**Comment by tbg2021** [comment]
Similarly (?) if one has a successful revolt in their country, you get the "rebels have toppled a spherelings govt" event rather than one for your own country.

**Comment by TheDeNuke** [comment]
That's mysterious. Both of them are mysterious.

Can you give me exactly what type of rebels toppled your country.

**Comment by tbg2021** [comment]
Doesn't matter, afaik. Had it happen with socialists, liberals, and iirc
reactionaries. Never had commie or fash rebels pop to see if they do as well

**Comment by TheDeNuke** [comment]
Only Socialists to be exact.

Everything else directs to the correct event.

**Comment by TheDeNuke** [comment]
Core Assimilation fixed.

It will abort when the government has full citizenship or the minorities are protected. It will not trigger if a government has either of the above.
