### ISSUE TITLE
Spanish Wars of Restoration

### ISSUE THREAD

**Issue by tbg2021** [TheDeNuke/DvD-Custom-Branch#9]
I've noticed in my latest run that there's a lot of ghost wars in the event of a partial spanish victory where Mexico holds together for a hot minute longer, but eventually collapses into a civil war while Spain starts sniping from the periphery. Currently they've been in ghost wars with all the native states in Mexico, as well as Jalisco (which was never released) and a second  ghost war with Mexico itself after annexing it.

**Comment by TheDeNuke** [comment]
I might look over the wars of restoration at some point. They are basically some of the oldest material in this mod and I've never touched them.
